### ISSUE TITLE
Error when building the solution

### ISSUE THREAD

**Issue by Perpete** [OPCFoundation/UA-.NETStandard-Samples#106]
Hello,

With visual studio 2019 version 16.8.3, after building the solution for your OPC UA .Net Standard Samples project, I find the following errors:

![UA Sample Applications - Microsoft Visual Studio](https://user-images.githubusercontent.com/66659162/103462246-26cc0b80-4d24-11eb-84e7-db465f8e7a5d.png)
(screen in french language) 

To solve the problem of .resx files, I check the Unblock box in their properties, on the General tab.

For the following errors:

- Metadata file 'D: \ Downloads \ Chrome_Téléchargement \ UA-.NETStandard-Samples-master \ UA-.NETStandard-Samples-master \ Samples \ Controls.Net4 \ bin \ Debug \ Opc.Ua.SampleControls.dll' not found

- Metadata file 'D: \ Downloads \ Chrome_Téléchargement \ UA-.NETStandard-Samples-master \ UA-.NETStandard-Samples-master \ Samples \ ClientControls.Net4 \ bin \ Debug \ Opc.Ua.ClientControls.dll' not found

What is the solution to solve this problem?

**Comment by mregen** [comment]
Hi @Perpete , do you have the output from the build window? This error list is sometimes completely off.
I'm using the same VS2019 version and I just tested 'UA Sample Applications.sln', all builds and works fine.

**Comment by Perpete** [comment]
Hello Mr. Mergen,
I reloaded the .zip file and unzipped it to another location.

Here is what the output of the build window gives:
The generation operation has started ...
1> ------ Start of generation: Project: UA Client Controls, Configuration: Debug Any CPU ------
2> ------ Start of generation: Project: Opc.Ua.Sample, Configuration: Debug Any CPU ------
1> C: \ Program Files (x86) \ Microsoft Visual Studio \ 2019 \ Community \ MSBuild \ Current \ Bin \ Microsoft.Common.CurrentVersion.targets (3075,5): error MSB3821: Unable to process Common \ ClientUtils file. resx because it is in the Internet or Restricted zone or it contains Mark of the Web. To process these files, delete Mark of the Web.
1> C: \ Program Files (x86) \ Microsoft Visual Studio \ 2019 \ Community \ MSBuild \ Current \ Bin \ Microsoft.Common.CurrentVersion.targets (3075,5): error MSB3821: Unable to process Common \ Client \ file EditComplexValue2Dlg.resx because it is in the Internet or Restricted zone or it contains Mark of the Web. To process these files, delete Mark of the Web.
3> ------ Start of generation: Project: UA Sample Controls, Configuration: Debug Any CPU ------
3> C: \ Program Files (x86) \ Microsoft Visual Studio \ 2019 \ Community \ MSBuild \ Current \ Bin \ Microsoft.Common.CurrentVersion.targets (3075,5): error MSB3821: Unable to process file ServerForm.resx because it is in the Internet or Restricted zone or it contains Mark of the Web. To process these files, delete Mark of the Web.
3> C: \ Program Files (x86) \ Microsoft Visual Studio \ 2019 \ Community \ MSBuild \ Current \ Bin \ Microsoft.Common.CurrentVersion.targets (3075,5): error MSB3821: Unable to process file Sessions \ TypeNavigatorCtrl. resx because it is in the Internet or Restricted zone or it contains Mark of the Web. To process these files, delete Mark of the Web.
2> Opc.Ua.Sample -> D: \ Documents \ Visual Studio 2019 \ Projects \ UA-.NETStandard-Samples-master \ UA-.NETStandard-Samples-master \ Samples \ Opc.Ua.Sample \ bin \ Debug \ net462 \ Opc.Ua.Sample.dll
2> Opc.Ua.Sample -> D: \ Documents \ Visual Studio 2019 \ Projects \ UA-.NETStandard-Samples-master \ UA-.NETStandard-Samples-master \ Samples \ Opc.Ua.Sample \ bin \ Debug \ netstandard2.1 \ Opc.Ua.Sample.dll
2> Opc.Ua.Sample -> D: \ Documents \ Visual Studio 2019 \ Projects \ UA-.NETStandard-Samples-master \ UA-.NETStandard-Samples-master \ Samples \ Opc.Ua.Sample \ bin \ Debug \ netstandard2.0 \ Opc.Ua.Sample.dll
4> ------ Start of generation: Project: UA Sample Client, Configuration: Debug Any CPU ------
4> CSC: error CS0006: Metadata file 'D: \ Documents \ Visual Studio 2019 \ Projects \ UA-.NETStandard-Samples-master \ UA-.NETStandard-Samples-master \ Samples \ ClientControls.Net4 \ bin \ Debug \ Opc.Ua.ClientControls.dll 'not found
4> CSC: error CS0006: Metadata file 'D: \ Documents \ Visual Studio 2019 \ Projects \ UA-.NETStandard-Samples-master \ UA-.NETStandard-Samples-master \ Samples \ Controls.Net4 \ bin \ Debug \ Opc.Ua.SampleControls.dll 'not found
========== Generation: 1 succeeded, 3 failed, 0 updated, 0 skipped ==========

Always the same problem.

**Comment by tukotech** [comment]
RE: because it is in the Internet or Restricted zone or it contains Mark of the Web
How did you get the source? Via git or zip? If zip, you have to remove alternate streams. See [streams](https://8thstring.blogspot.com/2019/12/unblocking-zip-or-exe-files-download.html) for details.

**Comment by Perpete** [comment]
Hello,
I just upload the zip code to Github.

![NETStandard-Samples](https://user-images.githubusercontent.com/66659162/104105114-5c38a200-52ac-11eb-925f-671d16a335f9.png)

**Comment by tukotech** [comment]
Have you tried to remove alternate streams? See https://8thstring.blogspot.com/2019/12/unblocking-zip-or-exe-files-download.html

**Comment by mregen** [comment]
I'd recommend to always use the 'git clone' command, then you can keep it up to date fairly easy.

**Comment by Perpete** [comment]
Hello,
I unzipped the .zip file with the 7-zip program.
Now it is working fine.
With the decompression program of windows 10, this does not work correctly.
When opening the solution in visual studio, I still get security warning messages related to an unreliable location source.
These messages do not appear after unzipping with 7-zip.

![Warning](https://user-images.githubusercontent.com/66659162/104549352-0446c600-5633-11eb-8a64-a25e148aabbc.png)

**Comment by tukotech** [comment]
Good news @Perpete. If you are all set, would you mind closing this ticket?
