### ISSUE TITLE
Trying to understand HistoricalAccess Server example.

### ISSUE THREAD

**Issue by andre-fm** [OPCFoundation/UA-.NETStandard-Samples#11]
Hello everyone,

I'm trying to understand how HistoricalAccess Server Example works. Using UAExpert with Historical Access View I manage to access to some kind of samples saved in .txt files (Boolean.txt, String.txt...) that are inside of "Dynamic" and "Sample" folders. But my goal here is to understand how that files are created or how I can use this kind of Historical Server with my Nodeset2.xml file. Is there some documentation about this HistoricalAccess Server example?
Thanks.

Regards,
André

**Comment by albrookesplowman** [comment]
I am also trying to understand the historian samples and I have also looked at the workshop projects but I am slightly confused as to what is possible.  I would like to be able to read the historical values for a particular node/tag and then get notification when a value changes for this node/tag...  Is this possible and do you know which section of code would be a good place to look?  Many thanks, Al
