### ISSUE TITLE
Xamarin demo client for Android hangs on connect

### ISSUE THREAD

**Issue by trofimich** [OPCFoundation/UA-.NETStandard-Samples#12]
I've compiled original "UA Xamarin Client" solution and tried to run it on my Android 8.1 device and found that i can't connect to OPC-UA server. Application simply hangs on connection attempt.

During debugging i found that the problem is in the file Opc.Ua.Core/Security/Certificates/DirectoryCertificateStore.cs line 613:

`entry.Certificate = new X509Certificate2(file.FullName);`

This line of code never finishes. I tried to comment this code, but it hangs further (also when trying to make some manipulations with certificates).

So, the sample is completely broken :-/

**Comment by leafgreen-0312** [comment]
"object reference not set to an instance of an object".
I have this exception when I enter the endpoint in Xamarin Client. Can you help me about that. Thanks a lot.

**Comment by romanett** [comment]
xamarin was deprecated as of 11/2024
