### ISSUE TITLE
UWP OPC UA Server in Raspberry Pi 3B with Windows IoT

### ISSUE THREAD

**Issue by fajunqueira** [OPCFoundation/UA-.NETStandard-Samples#123]
I would like to know if it would be possible to use the OPC UA Server from the "UA Universal Windows.sln" project on the Raspberry Pi 3B with Windows IoT.
To test it, I initially tried to run the server and client for this project on the same Windows 10 PC. Both run. On the client, when asking to connect to the server, a screen is presented with parameters already filled in. I didn't change anything. I clicked "OK". The message "Endpoint information may be out of date because the discovery process has not completed. Continue anyway?" appears. I selected "Yes". The exception is shown: "Caller: EndpointSelectorCTRL_ConnectEndpoint; Exception: Value cannot be null; Parameter name: serverCertificate".
I ran the client and server from the "DataAccess" folder of the "UA Quickstart Applications.sln" project without any problems.

**Comment by fajunqueira** [comment]
I debugged a little bit more. Apparently it is a certificate issue.
Only now I have noticed that the client application is "client and server". When trying to connect to the destination "opc.tcp://localhost:61210/UA/SampleClient", the certificates were found and the connection is established.
When trying to connect to the destination "opc.tcp://localhost:51210/UA/SampleServer", the certificate was not found.
Analyzing the folder "C:\ProgramData\OPC Foundation\UA\pki\rejected\certs\", 4 certificates are listed: "UA Core Sample Server"; "Quickstart Views Server"; "UA Sample server" (which I'm trying to connect to); and "Quickstart DataAccess Server".

In the file "ConfiguredServerDlg.xaml.cs", function "DiscoverEndpoints" (line 1059), it accesses the function "DiscoveryClient.Create" (line 1065) and it is where the app cannot find the server certificate. From there I don't have access to the "OPC.UA.Core.dll" code to continue to track and understand where and how the certificate is consulted.

**Comment by mregen** [comment]
Hi @fajunqueira, there is since a while support for source link to debug issues like this:

- Support for symbol snupkg packages on Nuget.Org. See [devblog](https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/) for more information on how to setup the debug symbol server.
- Support for [Sourcelink](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) for integrated source code debugging experience.

**Comment by mregen** [comment]
please reopen if issue was not resolved
