### ISSUE TITLE
GDS on Linux

### ISSUE THREAD

**Issue by RakshanPremsagar** [OPCFoundation/UA-.NETStandard-Samples#124]
Hello, 
I have been trying to run the GDS server on my Ubuntu 20,04. I have installed the consoleGDS server on my linux machine. Would want to explore the discovery options available. I would like to klńow if there is a console client application as well which could call the queryServers method? or the register application method?

Is the current implementation of the GDS only for windows operating system,apart from the consoleserver?
PS: Totally new to  GDS.

Regards,
Rakshan

**Comment by ZbynekZ** [comment]
You can use our OpcCmd Utility. Works on Windows/Linux/macOS (.NET required). Download: https://kb.opclabs.com/Tool_Downloads#OpcCmd_Utility .

The tool has many usages and features, and the documentation is sketchy. However, the part you are interested in has a tutorial, here: https://kb.opclabs.com/OPC_UA_Client_Application_Operations_in_OpcCmd#Tutorial

Best regards

**Comment by RakshanPremsagar** [comment]
Hello @ZbynekZ ,
First of all, thank you so much for your reply.
I installed the OpenCmd utility, and  I also have the console GDS Server running on my machine.
When I direct towards the OpenCmd folder and open the command prompt there,
 and i run the commands, I do not get any fruitful response. The first command from the tutorial : "uaClient getService uaClientApplication" , I get an error saying 
```
"Command 'uaClient' not found, did you mean:

 command 'uaclient' from deb python-opcua-tools (0.98.9-1)"

```
Are there any dependencies here? 

Also, am I understanding the scenario right?
I have 2 hosts. host A and host B. Both the hosts have the LDS-ME enabled. Host A has an extra OPC UA server which registers to its local LDS ME.
Now Host B is also aware of the extra OPC UA server along with the LDSME of host A. So totallly 3 Servers. 
All the hosts are on the Same LAN

I plan to have a centralised discovery mechanism which can be extended across the network. So I make use of the consoleGDSServer. I register the host B LDS ME to the GDS. Now GDS is aware of all the servers in the network.

Is it the correct use of GDS? and Can it be achieved using the console server here?
Kindoff clueless as I do not find examples to relate with.
Looking forward for your guidance.

Regards,
Rakshan

**Comment by ZbynekZ** [comment]
Hello.

You need to actually start the program first. The command you tried ("uaClient") needs to be entered inside the OpcCmd utility. Those are not commands for the OS shell. The tutorial tells you to enter these commands "at the OpcCmd>" prompt.

Installation: https://kb.opclabs.com/Category:OpcCmd_Utility#Introduction

**Usage: https://kb.opclabs.com/Category:OpcCmd_Utility#Usage .**

Use the "-i" (or "--interactive") option when starting the program. So, the command to get you started will probably look like:

     dotnet OpcCmd.dll -i

If the discussion gets too focused on the OpcCmd utility itself, I suggest that you take it to our Online Forums: https://www.opclabs.com/forum/opccmd-utility

Best regards
