### ISSUE TITLE
Mapping of C# objects to OPCUA

### ISSUE THREAD

**Issue by rajexlnc** [OPCFoundation/UA-.NETStandard-Samples#141]
I am new to OPC UA,
 
Our requirement is that the OPC UA Client app will do the reads/write data from/to a backend system (which is the system of record) via a OPC UA server. How can we represent the backend system C# objects in an OPC UA Server? So that the data gets directly updated in the backend system rather being on nodes(nodes object), we are more concerned on the duplicate  data in both places (OPC UA server and Backed system) and also the data need to be UPTODATE on both the OPCUA server and backend system.
Please Help

**Comment by tukotech** [comment]
The [NetCoreConsoleServer](https://github.com/OPCFoundation/UA-.NETStandard-Samples/tree/master/Samples/NetCoreConsoleServer) might be a good start.
