### ISSUE TITLE
Stable certificate in docker

### ISSUE THREAD

**Issue by kristianmo** [OPCFoundation/UA-.NETStandard-Samples#146]
It is an OPC UA server based on the HistoricalEvents Server in the quickstart. It is running in a linux docker container in .Net core 5.0. 

Every time the docker is recreated it will create a new certificate, requiring existing clients to accept the new certificate. I assume that the auto generated certificate logic is using HW information when the server starts to check whether to regenerate the certificate. Meaning my mapped certificate directory for the docker image looks like this.
![image](https://user-images.githubusercontent.com/32481434/114530043-df221d80-9c4a-11eb-83a9-5defdabf45bf.png)

In addition, as a test the server is deployed in a container instance in Azure with a fixed public IP, and clients complain that the certificate IP/host does not match the public IP, which is correct.

Are we able to disable the auto generation of certificates and tell the server what certificate to use?

**Comment by AlinMoldovean** [comment]
Hi @kristianmo ,

The application generates a self signed instance certificate only in case  it does not find the certificate specified in ApplicationConfiguration.SecurityConfiguration.ApplicationCertificate.

You need to make sure that a valid certificate exist at that specified configuration location in order to avoid the generation of a new certificate.

**Comment by kristianmo** [comment]
Thank you @AlinMoldovean. I generated a public certificate in der format like so:

1. Make a private key in openssl
2. Make a pem file in openssl
3. Create der from pem file using openssl
4. Copy the der file to OPC Foundation/pki/own/certs folder

and chose that in the configuration. I assume that the subject name must match exactly the subject of the certificate I made?
![image](https://user-images.githubusercontent.com/32481434/114576520-81f29000-9c7b-11eb-9d95-a760188f91c3.png)
![image](https://user-images.githubusercontent.com/32481434/114577067-00e7c880-9c7c-11eb-9ed1-56074afea28a.png)

This gives me an exception for access to private key.
![image](https://user-images.githubusercontent.com/32481434/114577373-3d1b2900-9c7c-11eb-9858-37746f9a3e44.png)

**Comment by mregen** [comment]
@kristianmo, did you copy the .pfx with private key to pki/own/private? 

There is some description here how to create a [custom cert](https://vslepakov.medium.com/custom-x509-certificates-with-opc-publisher-73a0127bf884)  with [scripts ](https://github.com/vslepakov/iot-edge/tree/master/opc-ua-certs)

Some extensions need to be properly filled out or if the private key is not found, a new cert is generated.

**Comment by kristianmo** [comment]
Thank you. I can share my further "exploration".

*Standalone server - your own certificates.*
1. Used the two links above to generate certificates matching the local computer and any other external IPs it can be accessed on.
2. Placed server der file in pki/own/certs, pfx in pki/own/private, added the root, intermediate, and server certificate to pki/trusted/certs
3. In the XML configuration make sure the <SubjectName> matches the SubjectName of the generated certificates
![image](https://user-images.githubusercontent.com/32481434/115216601-f195ce80-a104-11eb-90dc-7257861b479c.png)
![image](https://user-images.githubusercontent.com/32481434/115216716-10946080-a105-11eb-82e7-ce722454d38c.png)

*Standalone server - generated*
1. If you have multiple addresses/domains that the server can be accessed over it seems that you can specify AlternateBaseAddresses in the XML configuration and the server will generate a certificate with multiple IPs/domains
 
*Docker/Kubernetes - your own certificates*
By using IPs only and no domain names I got a stable certificate for docker. I have not tested Kubernetes yet, but I assume it will be stable in each pod if a docker is stable.
1. Used the two links above to generate certificates matching the external IPs the container can be accessed on, no domain names.
2. The base address and and the alternate base addresses in the XML configuration also only contains IPs and not domains.
