### ISSUE TITLE
Timestamp of HDA data giving timestamp which is 10 hours before current time

### ISSUE THREAD

**Issue by Praveen-g99** [OPCFoundation/UA-.NETStandard-Samples#179]
hi i used kepserver_HDA  server, in UAExpert i can see source timestamp  and server timestamp 10hrs difference can i get to know  why .

Any help is highly appreciated :)

**Comment by mregen** [comment]
Hi @Praveen-g99, this question is better suited for stackoverflow or you should talk to the server vendor. [Here](https://reference.opcfoundation.org/v104/Core/docs/Part4/7.7.4/) you can find the spec to server/source timestamp. Hope this helps.
