### ISSUE TITLE
Questions about sample GDS 

### ISSUE THREAD

**Issue by darlene4** [OPCFoundation/UA-.NETStandard-Samples#183]
Hello everyone,

I'm new to working with OPC UA and I'm trying out this sample GDS with sample client and server and I have few questions if you could answer me.

- Is it possible to change certificate validation period (to edit it in code)?
- Does GDS support certificate renewal and revocation?
- Would it be possible to edit sample client to connect to GDS without using GDS Agent?
- Does sample server support push management?

Thank you,
Lena

**Comment by mregen** [comment]
Hi @darlene4, some answers inline, hope this helps

>     * Is it possible to change certificate validation period (to edit it in code)?
There is a configuration section for GDS to set default lifetimes in the app config file
>     * Does GDS support certificate renewal and revocation?
Yes
>     * Would it be possible to edit sample client to connect to GDS without using GDS Agent?
yes, that would use a Client GDS Pull. The GDS client nuget packages contains the necessary classes.
>     * Does sample server support push management?
The ref server supports the GDS Push, but only with hardcoded credentials

Cheers,
Martin

**Comment by darlene4** [comment]
Thank you for your answer!

If you could please answer me on one more question. I would like to know what will happen if client application is only register to GDS and using the self-signed certificate (not the one from GDS) and when that certificate expires. How would the revocation go? Would the client still be able to communicate with previously connected servere?

**Comment by mregen** [comment]
> 1. Should the certificate from GDS CA (IOP-2017 CA) be added in GDS´s trust list (somewhere in the configuration file) because currently GDS doesn't trust the certificates that were signed by its own CA?

The GDS uses normally auto accept, so it is not needed to be in its own trustlist.

> 2. When a client registers on a GDS with a self-signed certificate, why is that certificate not added to the trust list so that the client can communicate with online servers without any additional certificate approvals?

Thats a manual step that would be done by an admin, to decide which certs happen to be in the trustlist.
