### ISSUE TITLE
Xamarin can't select endpoint with server have sercurity

### ISSUE THREAD

**Issue by nhattran2108** [OPCFoundation/UA-.NETStandard-Samples#20]
I have create a server OPCUA. In the "SAME CODE", I have used Client UA.Net to connect it successed, but when use Xamarin its not and have problem in selected endpoint ,return "Error establishing a connection: BadNotConnected" . How to fix it. Thanks
![image](https://user-images.githubusercontent.com/48618235/86764666-66b27e80-c072-11ea-82a0-2d86ea500e8a.png)

**Comment by romanett** [comment]
xamarin was deprecated as of 11/2024
