### ISSUE TITLE
I don't know to call a method passing input parameteres

### ISSUE THREAD

**Issue by kuhdav** [OPCFoundation/UA-.NETStandard-Samples#21]
I should call the method: "GenerateFileForRead". 

![immagine](https://user-images.githubusercontent.com/11340928/86895594-fe60ad00-c104-11ea-9c41-0628da3d5e22.png)

The problem is that I don't know how to set the Input Parameter which I should pass to the method
When I Use the UaExpert and call this method:

![immagine](https://user-images.githubusercontent.com/11340928/86896895-fefa4300-c106-11ea-9dc7-d79bcae4a745.png)

I see the method wants a "ProductionDatasetReadOptionsType but I don't know how get it to modifiy as in the picture above
I know its node Id but but how derive the type from it?
Anybody can help me?

**Comment by benjamin1988** [comment]
@kuhdav 
Did you still have problems calling the function?

**Comment by tobiasdroessler** [comment]
I have similar problems to get user- or server defined (deep structured) types from the server and then fill up a object of that kind to use as in parameter for the method call. 

 By there way the server is a Siemens S7 Plc.

**Comment by benjamin1988** [comment]
@tobiasdroessler 
How do you call the method? Can you may provide a code snippted? Especially with the ProductionDatasetReadOptionsType?

**Comment by tobiasdroessler** [comment]
.. the Call is not a problem. The Problem is how to create a object containing the requirements from a custom defined type at the server. I do not know the specific ProductionDatasetReadOptionsType  ... i thought its a custom type someone created on a server side.

**Comment by benjamin1988** [comment]
@tobiasdroessler 
As the server has to know the type you can create a local class and add the information out of the custom type of the OPC ua server. Afterwards you should be able to call the Method with the argument. To create the class you can derive from StructureDefinition and set the BinaryEncoding, DefaultEncoding, XmlEncoding, TypeId usw. this information you can get from the OPC UA server. 
Then you add the necessary properties and then you should be able to call the method with an instance of this class.

**Comment by tobiasdroessler** [comment]
thank you. 

I will describe the case more detailed. @benjamin1988 may you can provide a code snipped or steps to reach this. 


I am working on a gateway solution, which contains a Opcua client to access (read) data and Call methods. 
So there different opcua servers/... a static solution for custom types are not suitable is noted here.
I will rec. method call input argument payload in a JSON format. 

I have read some Issues here and hab a look at the complex types sample inside the sample repo .. and tried out.. but the trail and error code was not working or get me further to understand.  

Here are the steps I have in mind:

* read method input argument Type(s)
* ((If custom Type)): Retrive specific type Information from the Server
* create an new object from type above and fill in values from input data  json source. 
* call method with argument object above.

I am not sure if this the way to go?  I not very deep familiar with Opcua custom types (and the different kind of types in opcua spec) and what information are provided by the server...  encoding ,.. 

may there is a document on this topic, helping me to understand what it sould be.

**Comment by benjamin1988** [comment]
@tobiasdroessler 

We have implement an interpreter which generates assemblies but I don't think that this is necessary in your case. 

May you can take a look to the questions in Ua-.NetStandard repository:
https://github.com/OPCFoundation/UA-.NETStandard/issues/243

If you have questions don't hesitate to ask.
