### ISSUE TITLE
configuration at runtime

### ISSUE THREAD

**Issue by kamishuki76** [OPCFoundation/UA-.NETStandard-Samples#22]
Hi. I'm trying to change server configuration at runtime. But a problem is when i save new configuration into an xml file and reload again. It has error " could not load configuraion file". 
This is my form code to change the security Policy of Server
`#region Private Field
private StandardServer m_server;
private ApplicationConfiguration m_configuration;
private ApplicationInstance m_application;
public ServerSecurityPolicy Policy { get; private set; }
    #endregion
    #region Constructor
    public EndpointCtrl()
    {
        InitializeComponent();
    }
    #endregion
    #region Public Interface       
    public void Initialize(StandardServer server, ApplicationConfiguration configuration, ApplicationInstance application)
    {
        m_server = server;
        m_configuration = configuration;
        m_application = application;
        ComboBox adlist = new ComboBox();
        foreach (EndpointDescription endpoint in m_server.GetEndpoints())
        {
            if (adlist.FindStringExact(endpoint.EndpointUrl) == -1)
            {
                adlist.Items.Add(endpoint.EndpointUrl);
            }
        }
        TCP_Adresss_Label.Text = "(" + adlist.Items[0].ToString() + ")";
        HTTPS_Address_Label.Text = "(" + adlist.Items[1].ToString() + ")";
        UA_AddressTB.Text = adlist.Items[0].ToString();
        HTTPS_AddressTB.Text = adlist.Items[1].ToString();
        CheckPolicies(m_configuration);
// m_configuration.ServerConfiguration.BaseAddresses.
}
#endregion

    #region Methods
    private void CheckPolicies(ApplicationConfiguration configuration)
    {
        try
        {
            foreach (ServerSecurityPolicy policy in configuration.ServerConfiguration.SecurityPolicies)
            {
                if (policy.SecurityMode == MessageSecurityMode.None) UA_SM_NoneCB.Checked = true;
                if (policy.SecurityMode == MessageSecurityMode.Sign) UA_SM_SignCB.Checked = true;
                if (policy.SecurityMode == MessageSecurityMode.SignAndEncrypt) UA_SM_Sign_EnCB.Checked = true;
                if (policy.SecurityPolicyUri == SecurityPolicies.Basic128Rsa15) Basic128Rsa15_CB.Checked = true;
                if (policy.SecurityPolicyUri == SecurityPolicies.Basic256) Basic256_CB.Checked = true;
                if (policy.SecurityPolicyUri == SecurityPolicies.Basic256Sha256) Basic256Sha256_CB.Checked = true;
            }
        }
        catch (Exception exception)
        {
            ServerUtils.HandleException(this.Text, exception);
        }
    }
    private void CheckSecurity()
    {
        try
        {

            ServerSecurityPolicy policy = new ServerSecurityPolicy();
            if (UA_SM_NoneCB.Checked)
            {
                policy = CreateSecurityPolicy(0, 0);
                Addpolicies(m_configuration, policy);
            }
            else
            {
                policy = CreateSecurityPolicy(0, 0);
                DeletePolicies(m_configuration, policy);
            };
            if ((UA_SM_SignCB.Checked)&&(Basic128Rsa15_CB.Checked))
            {
                policy = CreateSecurityPolicy(1, 1);
                Addpolicies(m_configuration, policy);
            }
            else
            {
                policy = CreateSecurityPolicy(1, 1);
                DeletePolicies(m_configuration, policy);
            }
            if ((UA_SM_Sign_EnCB.Checked)&&(Basic256Sha256_CB.Checked))
            {
                policy = CreateSecurityPolicy(2, 3);
                Addpolicies(m_configuration, policy);
            }
            else
            {
                policy = CreateSecurityPolicy(2, 3);
                DeletePolicies(m_configuration, policy);
            }                
        }
        catch (Exception exception)
        {
            ServerUtils.HandleException(this.Text, exception);
        }
    }
    private void Addpolicies(ApplicationConfiguration configuration, ServerSecurityPolicy polici)
    {
        try
        {
            int i = 0;
            foreach (ServerSecurityPolicy policy in configuration.ServerConfiguration.SecurityPolicies)
            {
                if (polici == policy) i++;
            }
            if (i == 0) configuration.ServerConfiguration.SecurityPolicies.Add(polici);
        }
        catch (Exception exception)
        {
            ServerUtils.HandleException(this.Text, exception);
        }
    }
    private void DeletePolicies(ApplicationConfiguration configuration, ServerSecurityPolicy polici)
    {
        try
        {
            int i = 0;
            foreach (ServerSecurityPolicy policy in configuration.ServerConfiguration.SecurityPolicies)
            {
                if (polici == policy) configuration.ServerConfiguration.SecurityPolicies.Add(policy);
                break;
            }
        }
        catch (Exception exception)
        {
            ServerUtils.HandleException(this.Text, exception);
        }
    }

    private ServerSecurityPolicy CreateSecurityPolicy(byte MessageMode, byte PolicyNumber)
    {
        try
        {
            ServerSecurityPolicy Policy = new ServerSecurityPolicy();
            switch (MessageMode)
            {
                case 0:
                    Policy.SecurityMode = MessageSecurityMode.None;
                    break;
                case 1:
                    Policy.SecurityMode = MessageSecurityMode.Sign;
                    break;
                case 2:
                    Policy.SecurityMode = MessageSecurityMode.SignAndEncrypt;
                    break;
                default:
                    Policy.SecurityMode = MessageSecurityMode.Invalid;
                    break;
            }
            switch (PolicyNumber)
            {
                case 0:
                    Policy.SecurityPolicyUri = SecurityPolicies.None;
                    break;
                case 1:
                    Policy.SecurityPolicyUri = SecurityPolicies.Basic128Rsa15;
                    break;
                case 2:
                    Policy.SecurityPolicyUri = SecurityPolicies.Basic256;
                    break;
                case 3:
                    Policy.SecurityPolicyUri = SecurityPolicies.Basic256Sha256;
                    break;
            }                
        }
        catch (Exception exception)
        {
            ServerUtils.HandleException(this.Text, exception);
        }
        return Policy;
    }

    #endregion

    #region Event Hanlder

    #endregion

    private void ApplyBtn_Click(object sender, EventArgs e)
    {
        try
        {
            CheckSecurity(); 
            m_configuration.SaveToFile(m_application.ConfigSectionName + ".Config.xml");
            m_application.LoadApplicationConfiguration(false);
        }
        catch (Exception exception)
        {
            ServerUtils.HandleException(this.Text, exception);
        }
    }
}
}`
I save this but when I Click apply setting to change the config and reload the server configuration. It has error
![image](https://user-images.githubusercontent.com/50210154/87237498-5c510580-c421-11ea-8ff1-71c6656fb122.png)
![image](https://user-images.githubusercontent.com/50210154/87237504-6541d700-c421-11ea-823b-e1738ea3b0ab.png)

Why is this happen??? Is any solution to solve this. Thank you.

**Comment by AlinMoldovean** [comment]
Hi @kamishuki76 ,

You get a null reference exception and you need to debug inside and find the exact place where it happens.
