### ISSUE TITLE
Data Access Interface Version 1.0  Not Supporting.

### ISSUE THREAD

**Issue by Praveen-g99** [OPCFoundation/UA-.NETStandard-Samples#230]
The OPC UA address space is not differentiated with Node Class ,when DA to UA converter is connected to OPC Classic Server(using KEPServer Interface Version 1.0) and it is exposing as folder type for all configuration.

 Find below attached screenshot for reference
1.ScreenShot1(DA Interface version 1.0)
![Interface1 0](https://user-images.githubusercontent.com/85987152/138847246-0dec8cb9-4fe4-4bfc-b7fe-5391b10f1dd4.png).
2.ScreenShot2(DA Interface version 3.0)
![Interface3 0](https://user-images.githubusercontent.com/85987152/138849093-5940e176-0db9-4858-aba3-a1ab879ae6e8.png).

**Comment by mregen** [comment]
@Praveen-g99 please add more description how to repro? What is DA Interface 1.0 vs 3.0?
