### ISSUE TITLE
GDS pull model method authorization

### ISSUE THREAD

**Issue by tjfortin** [OPCFoundation/UA-.NETStandard-Samples#231]
I am testing GDS pull functionality from within an embedded UA client.  Per the spec, I need to supply admin credentials when registering or unregistering the client application but should not need to provide admin credentials when calling the pull methods -- StartSigningRequest, FinishRequest, etc.  Instead (refer to section 7.6.3), "It can also be invoked by the Application that owns the private key used to sign the CertificateRequest (e.g. the private key shall be the private key used to create the SecureChannel).".  The sample GDS however rejects these pull model method calls with an access denied error and appears to only be checking for admin credentials on the session context.

**Comment by mregen** [comment]
Hi @tjfortin , I believe the topic was discussed and its not implemented in this GDS. I'll keep it for tracking, maybe somebody in the community has cycles to improve it.

**Comment by romanett** [comment]
The same is true also for the CertificateDirectory:getTrustList Method.
Common Clients e.g. UaExpert registered via GDS Pull try to call this method anonymously and fail to get this.

**Comment by romanett** [comment]
Hi @mregen I will try to implement this feature.

Currently i have this absolute mess of code, which als does not check for rejected certificates.
![image](https://github.com/OPCFoundation/UA-.NETStandard-Samples/assets/7413710/b3674a6e-f1b3-4380-89c9-f34e9d78b4e3)

Can you give me some hints which methods to call for better code?
I would try to directly check the ApplicationsCertificatesStorePath but I have no member to access the GlobalDiscoveryServerConfiguration Object?

**Comment by romanett** [comment]
What do you think about this implementation, is this sufficient?
![image](https://github.com/OPCFoundation/UA-.NETStandard-Samples/assets/7413710/32d38eb3-1641-470f-8d5f-fcdecdb7c2e7)


![image](https://github.com/OPCFoundation/UA-.NETStandard-Samples/assets/7413710/38104cc8-0709-4be8-b7b1-da9d3b278c18)

**Comment by mregen** [comment]
work in progress..

**Comment by romanett** [comment]
done
