### ISSUE TITLE
Including the source code form UA-.NetStandard

### ISSUE THREAD

**Issue by lida-3** [OPCFoundation/UA-.NETStandard-Samples#232]
I would like to use the source code from the Ua.-NetStandard Libraries to debug this project.
I positioned my repositories Standard and Sample next to each other and tried to use the source code for the GDS client. 
In GlobalDiscoveryClient.csproj insted of 
```
<PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Configuration">
      <Version>1.4.367.42</Version>
    </PackageReference>
 <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Gds.Client.Common">
      <Version>1.4.367.42</Version>
 </PackageReference>
```
I  included following project references:
```
<ProjectReference Include="..\..\..\..\UA-.NETStandard\Libraries\Opc.Ua.Configuration\Opc.Ua.Configuration.csproj">
      <Project>{de6b7d4f-e566-45cb-a876-086e5cd50fb0}</Project>
      <Name>Opc.Ua.Configuration</Name>
</ProjectReference>
<ProjectReference Include="..\..\..\..\UA-.NetStandard\Libraries\Opc.Ua.Gds.Client.Common\Opc.Ua.Gds.Client.Common.csproj">
      <Project>{0B97D07F-629D-47DD-8975-B1F96D434130}</Project>
      <Name>Opc.Ua.Gds.Client.Common</Name>
</ProjectReference>
```
And in the UA Client Controls.csproj insted of
```
<PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client">
      <Version>1.4.367.42</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client.ComplexTypes">
      <Version>1.4.367.42</Version>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Configuration">
      <Version>1.4.367.42</Version>
    </PackageReference>
```
I included:
```
 <ProjectReference Include="..\..\..\..\UA-.NETStandard\Libraries\Opc.Ua.Client\Opc.Ua.Client.csproj">
      <Project>{cd3c8738-1fbb-405d-aec0-92e76bf399a0}</Project>
      <Name>Opc.Ua.Client</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\..\..\UA-.NETStandard\Libraries\Opc.Ua.Client.ComplexTypes\Opc.Ua.Client.ComplexTypes.csproj" />
    <ProjectReference Include="..\..\..\..\UA-.NETStandard\Libraries\Opc.Ua.Configuration\Opc.Ua.Configuration.csproj">
      <Project>{de6b7d4f-e566-45cb-a876-086e5cd50fb0}</Project>
      <Name>Opc.Ua.Configuration</Name>
    </ProjectReference>
```

After I tried to build the GlobalDiscoveryClient project I got the
`error CS0433: Type TypeName1 exists in both TypeName2 and TypeName3`
e.g. The type 'GlobalDiscoveryServerClient' exists in both 'Opc.Ua.Gds.Client.Common, Version = 1.4.367.0, Culture = neutral, PublicKeyToken = bfa7a73c5cf4b6e8' and 'Opc.Ua.Gds.Client.04,' Opc.Ua.Gds. 04. , Culture = neutral, PublicKeyToken = null 'GlobalDiscoveryClient

And when I try to open any of these references that I included in the object browser, I get a message:
`This project cannot be viewed in the object browser because it is unavailable or not yet built`

Is there a better way to include the source code? Or what should I do to avoid duplicating types?

**Comment by mregen** [comment]
Hi @lida-3 , I think the best way for a .NET framework project is to first remove all references to the Opc.Ua Nuget packages in all projects.
Then you add the required projects from the stack to the solution.
Then you add the project references manually to each .NET project until stuff starts building.

For pure .NET core projects its a little easier, e.g. see https://github.com/OPCFoundation/UA-.NETStandard-Samples/blob/5bfe5e3d37bdb89970b32cdf509e629784c94b24/Samples/NetCoreConsoleClient/NetCoreConsoleClient.csproj#L18

the you add the projects to the solution and its working.
