### ISSUE TITLE
Example of how to use the new CertificateBuilder for creating a new certificate

### ISSUE THREAD

**Issue by anhame** [OPCFoundation/UA-.NETStandard-Samples#234]
Hello,

is there any example available of how to use the new CertificateBuilder in conjunction with the CertificateFactory class?

thanks in advance!
Hartmut

**Comment by mregen** [comment]
Hi @anhame , in the test cases are a couple of samples: https://github.com/OPCFoundation/UA-.NETStandard/blob/8c1a659ecf5c1616b3b7f132706324b90f9ff015/Tests/Opc.Ua.Core.Tests/Security/Certificates/CertificateFactoryTest.cs#L92

**Comment by mregen** [comment]
hopefully answered
