### ISSUE TITLE
GDS root certificate and CA root certificate

### ISSUE THREAD

**Issue by darlene4** [OPCFoundation/UA-.NETStandard-Samples#235]
Hi,

I have a questions regarding GDS and CA root certificates.
What will happen when GDS certificate expires? How will it be renewed? 
Also, what will happen when CA certificate expires (the one that signs all application certificates)? Will the application signed by it be able to communicate securely with others? Will it be added to revocation list and the renewed one on trust list?
Could you please explain a little bit about what that process would look like?

Thank you!

**Comment by mregen** [comment]
> What will happen when GDS certificate expires? 

Under normal circumstances the GDS certificate should be renewed before the lifetime of the issued certificate is affected. E.g. the issued certs have a lifetime of 2years, the GDS cert of 5 years, then somewhat before the lifetime of the issued certificates is shortened (e.g. before the GDS cert has a lifetime of less than 2 years) the GDS cert should be renewed.

>How will it be renewed?

In this GDS sample a new public/private key pair would manually replace the GDS CA certificate. The 'old' certificate is still valid for some time and the CRL must still be maintained, so the root CA would still remain in the trust lists for devices until life time ended.
(Revoking expired app certs is not implemented in this sample code)

>Also, what will happen when CA certificate expires (the one that signs all application certificates)? 
Then it can be removed from the GDS and the trust lists on the GDS. However many applications still allow to communicate with expired certificates, so it is the decision of the admin to completely remove it or to keep it to allow for validating cert chains, even if certificates are expired.

>Will the application signed by it be able to communicate securely with others? 
If you mean after the cert expires, it depends on the UA application settings.

>Will it be added to revocation list and the renewed one on trust list?

No, as many applications will still rely on the CA cert until it is expired and their signed app certs are renewed with a new cert.

>Could you please explain a little bit about what that process would look like?

Hopefully that was covered...
