### ISSUE TITLE
Is there a sample of a client connect to a DA server?

### ISSUE THREAD

**Issue by tcsabina** [OPCFoundation/UA-.NETStandard-Samples#268]
Hello,

Not really an issue, but rather a question:
Are there any example codes in this project that connects a client to a DA server?

Regards,
Tamas

**Comment by mregen** [comment]
Do you mean OPC Classic DA?

**Comment by tcsabina** [comment]
HI mregen,

Yes, I mean the classic DA.

**Comment by mregen** [comment]
A sample is the [ComIOP](https://github.com/OPCFoundation/UA-.NETStandard-Samples/tree/master/ComIOP) solution.
