### ISSUE TITLE
Need correct steps to setup OPC UA Server and OPC UA Client with Reverse connection.

### ISSUE THREAD

**Issue by aravinds4uAll** [OPCFoundation/UA-.NETStandard-Samples#29]
Hi friends,

Can you please guide me the correct steps/sequence to run an OPC UA Server with reverse connection and connect an OPC UA Client with reverse connection. I badly need it for my work to complete. Please guide me on which project to build and run first followed by the other. Basically the sequence. Also please do guide me on any hacks or extra steps to be taken care for reverse connection to work.

Please also guide me on what exactly needs to be passed to the reverse connection manager uri. and also the Server uri. I am getting confusion over this in the OPC Client with reverse connection.

I could see lot of Server and Client projects, So really getting baffled around on which project to pick up and the correct sequence to be followed. Please help.

Thanks & Regards
Aravind S.

**Comment by aravinds4uAll** [comment]
Please also guide me on what exactly needs to be passed to the reverse connection manager uri. and also the Server uri. I am getting confusion over this in the OPC Client with reverse connection.

**Comment by xky0007** [comment]
Hi, I'm facing the same problem. Is there any update? I tried to follow the example description [here](https://github.com/OPCFoundation/UA-.NETStandard/blob/master/Docs/ReverseConnect.md). But it doesn't work.

**Comment by mregen** [comment]
see https://github.com/OPCFoundation/UA-.NETStandard/blob/master/Docs/ReverseConnect.md
latest nuget packages (1.4.363) fixed a few issues and have improvements.

**Comment by xky0007** [comment]
@mregen Thanks. I checked the doc but it didn't mentioned which client should be opened for incoming connection and which server should be used to initial a reverse connection. Can you specify both project name and path?
`Only a limited number of samples is available yet, the Reference Server, the Aggregation Server and the Console server and client.`

**Comment by mregen** [comment]
Hi @aravinds4uAll, I found a few small issues in the NetCoreConsole samples, please check out #52. Other samples work only by specifying the Reverse Connect configuration entries. Hope this helps to get started.
