### ISSUE TITLE
UAView Example

### ISSUE THREAD

**Issue by andythinkiq** [OPCFoundation/UA-.NETStandard-Samples#346]
Hi Everyone,

I'm looking for an example of UAView, but couldn't find any. I have searched in the companion specs NodeSet files and all example projects with no luck. Please point me in the right direction if you have any information.

Thanks,
Andy

**Comment by mregen** [comment]
see View sample here: https://github.com/OPCFoundation/UA-.NETStandard-Samples/tree/master/Workshop/Views

**Comment by andythinkiq** [comment]
Thank you!!!
