### ISSUE TITLE
Subscription recreation not happening on UA Client when UA Com Server Wrapper restarted.

### ISSUE THREAD

**Issue by Praveen-g99** [OPCFoundation/UA-.NETStandard-Samples#426]
When we restart the UA COM Server Wrapper with the underlying DA server that contains bulk tags(up to 10k subscribed), the subscription is not bring recreated in the UA client (UA expert).

**Configuration Details:**

**DA Server name** : KepServer
**OPC UA client**: UA Expert
**configuration** :1 channel, 5 device, each device having 4k tags, total tags 20k.
<img width="960" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/85987152/196420585-fe55f5c3-db38-461b-a641-e607c9247198.png">

**Current Behaviour**: the subscription is not being recreated when the server is restarted & the items are getting removed from Data Access view.
<img width="960" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/85987152/196420284-6d1177f7-9307-4aa0-ac12-9992605e46f1.png">

**Expected Behaviour**: In the UA client's data access view, all subscribed tags should be recreated once UA COM Server Wrapper is Restarted and their values should start updating.

**Steps to reproduce:**

1. Start UA COM Server Wrapper & Connect Using UA client. (UA Expert)
2. In the UA client, creating four data access instances and subscribing the bulk tags to the four data access views.
3. Restart the UA COM Server Wrapper

**Environment:**

**Windows**: Windows 10 Pro
**Installed RAM**: 16 GB
**System Type**: 64 bit

**Comment by romanett** [comment]
ua com interop was deprecated as of 11/2024
