### ISSUE TITLE
Unable to find projects for console

### ISSUE THREAD

**Issue by 2mik** [OPCFoundation/UA-.NETStandard-Samples#441]
Recently the samples repository contained console applications, such as NetCoreConsoleClient and NetCoreConsoleServer. They were simple and helped to faster understand how OPC UA works, because they had no UI. Currently these apps were removed.
May I ask if those apps removed completely or moved somewhere else, and why?
Thank you.

**Comment by mregen** [comment]
Hi @2mik , the console samples were integrated into the core repository [here](https://github.com/OPCFoundation/UA-.NETStandard/tree/master/Applications/ConsoleReferenceClient) and became obsolete, because they contained duplicate functionality.

**Comment by 2mik** [comment]
Thank you for the answer.
