### ISSUE TITLE
Support for reverse discovery

### ISSUE THREAD

**Issue by Desmond-J** [OPCFoundation/UA-.NETStandard-Samples#463]
Type of Issue
[ ] Bug [ ] Enhancement [ ] Compliance [x ] Question [ ] Help wanted

Hi, I'd like to implement a reverse discovery feature in my own OPCUA client tool with OPCFoundation UA-.NETStandard lib, like the one in UaExpert as below:
![image](https://user-images.githubusercontent.com/55578867/213377874-19812bcc-d0db-4769-9ed0-0458dbe67cd4.png)

But I failed to do that. So I'd like to know if reverse discovery is supported in OPCFoundation UA-.NETStandard.

Thank you

**Comment by mregen** [comment]
@Desmond-J should be possible, if not we need to fix it

**Comment by Desmond-J** [comment]
@mregen 
Hi, I've tried to find some sample code from "UA Global Discovery Server" project and the DiscoveryClient is the only class that I thought perform the actual discovery action.

I've try to copy the discovery code from "UA Global Discovery Server" project and the normal discovery works as expected. But I struggle to make reverse discovery work.

I'll attach my demo code here.

[demo_code.txt](https://github.com/OPCFoundation/UA-.NETStandard-Samples/files/10532785/demo_code.txt)

UaExpert can reverse discovery the URI in the demo code successfully.

Since I don't have too much experience in OPCUA programming, do you have any suggestion? Or did I just do it completely wrong and there should be another way to implement reverse discovery?

**Comment by mregen** [comment]
@Desmond-J did it work in the end?

**Comment by Desmond-J** [comment]
It turned out that in the end our software design framework cannot support this reverse discovery feature, no matter if UA-.NetStandard support or not. I have to give up and find a workaround solution.

**Comment by Desmond-J** [comment]
@mregen Hi, even though our current product cannot support the reverse discovery, we would still like to know how to implement this feature with UA-.NetStandard SDK. Because this feature is still on our road map in the feature and I haven't figured out how to make it work.

The sample code I found in "UA Global Discovery Server" project works in normal discovery case but failed in reverse case. Is there any sample code specific for reverse discovery?

Thanks.
