### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by RanP-A** [OPCFoundation/UA-.NETStandard-Samples#556]
### Type of issue

- [ ] Bug
- [ ] Enhancement
- [ ] Compliance
- [ ] Question
- [X] Help wanted

### Current Behavior

Issue Summary:
Despite having the most recent version of Visual Studio 2022 installed along with all the required add-ons, I'm experiencing challenges when trying to run the UA-.NETStandard-Samples project.

Project Objective:
My goal is to run a client that interacts with a controller acting as a server.

Specific Concerns:

Installation: I have ensured that I have the latest version of Visual Studio 2022 and all necessary add-ons installed on my system.

Running Samples: However, when attempting to run the UA-.NETStandard-Samples project, I encounter issues that prevent the successful execution of the client.

Troubleshooting: I have followed the provided documentation closely and attempted to troubleshoot the problems I'm encountering. Despite my efforts, I'm unable to identify the root cause of these issues.

I am seeking your guidance to understand why I might be facing these challenges and to seek assistance in resolving them. Your expertise and insight would be invaluable in helping me overcome the obstacles and achieve success with the UA-.NETStandard-Samples project.

If you require any additional information about my system setup, the specific errors I'm encountering, or any logs that could help diagnose the issue, please let me know, and I'll be more than happy to provide them.

Thank you very much for your time and consideration. I greatly appreciate your support in helping me address these problems and move forward with my project.

Looking forward to your response.

Best regards,
Ran

### Environment

```markdown
- OS:
- Environment:
- Runtime:
- Nuget Version:
- Component:
- Server:
- Client:
```

**Comment by mregen** [comment]
@RanP-A please reopen if you can provide specific information
