### ISSUE TITLE
Files Management in OPC.UA - 

### ISSUE THREAD

**Issue by JoseGR-C** [OPCFoundation/UA-.NETStandard-Samples#59]
Hellow everyone,
I'm trying to implement Files in my Opc.Ua server C#. I haven't got much experience in Opc.ua (a couple of weeks) but in documentation I've seen the ObjectType FileType. I've found it in me solution in Opc.Ua.Core\Stack\Generated\Opc.Ua.Classes.cs(4320). My beginner problem is that I'm not able to declare a  instante in my AdressSpace :
FyleType myfile. 
The avalible options are : FileDirectoryState, FileState or UABinaryFileDataType.
I'm able to create folders and simples variables/events and watch them in my client but files imposible. 
Thank you.

**Comment by AlinMoldovean** [comment]
Hello @JoseGR-C ,

In order to create an instance of FileType object in Address Space you need to use the _FileState_ class.
Here is a code sample to use in `ReferenceNodeManager.CreaetAddressSpace()`
```
                    FileState fileState = new FileState(root);

                    fileState.SymbolicName = "FileStateInstance";
                    fileState.ReferenceTypeId = ReferenceTypes.Organizes;

                    fileState.Create(SystemContext,
                        null,
                        new QualifiedName("FileStateInstance", NamespaceIndex),
                        new LocalizedText("en", "FileStateInstance"),
                        true);

                    root.AddChild(fileState);
```

**Comment by JoseGR-C** [comment]
> 
> 
> Hello @JoseGR-C ,
> 
> In order to create an instance of FileType object in Address Space you need to use the _FileState_ class.
> Here is a code sample to use in `ReferenceNodeManager.CreaetAddressSpace()`
> 
> ```
>                     FileState fileState = new FileState(root);
> 
>                     fileState.SymbolicName = "FileStateInstance";
>                     fileState.ReferenceTypeId = ReferenceTypes.Organizes;
> 
>                     fileState.Create(SystemContext,
>                         null,
>                         new QualifiedName("FileStateInstance", NamespaceIndex),
>                         new LocalizedText("en", "FileStateInstance"),
>                         true);
> 
>                     root.AddChild(fileState);
> ```

It works! Thank you so much!
