### ISSUE TITLE
Unregister Application is not deleting corresponding rows in CertificateStores

### ISSUE THREAD

**Issue by sveinfolkeson** [OPCFoundation/UA-.NETStandard-Samples#605]
### Type of issue

- [X] Bug
- [ ] Enhancement
- [ ] Compliance
- [ ] Question
- [ ] Help wanted

### Current Behavior

When trying to unregister an application in GlobalDiscoveryClient you get an exception because the belonging CertificateStore rows are not deleted before the applicaion is deleted

### Steps To Reproduce

Register and unregister an application in GlobalDiscoveryClient

### Environment

```markdown
- OS: Win11
- Environment: Visual Studio 2022
- Runtime: .NET 4.8
- Nuget Version: 1.5.374.27
- Component: Opc.Ua.Gds.Server.Database.Sql
- Server: GlobalDiscoveryServer
- Client: GlobalDiscoveryClient
```

**Comment by romanett** [comment]
This is fixed by mentioned PR
