### ISSUE TITLE
IOPCSecurityPrivate  interface fail to create

### ISSUE THREAD

**Issue by asgaralim** [OPCFoundation/UA-.NETStandard-Samples#61]
Hi Everyone,

This is regarding UA COM Interop Library IOPCSecurityPrivate.Logon method.  I have a server (clear scada) which support the private security (IOPCSecurityPrivate) interface.

The COM wrapper Calls Set Identity method. This method Creates the IOPCSecurity object and call the method Logon.  It throws exception while loading the IOPCSecurity interface object. Could you please suggest resolution for this issue. 

It is also observed that sometime, set Identity method successfully create/load the IOPCSecurity object. Most of the time it fails to load/create.

Below is the log message. But clearscada supports private security. Sometimes it connects successfully and sometime it throws exception.
5/8/2019 15:28:40.052 : IOPCSecurityPrivate.Logon NotSupportedException 'COM interface 'IOPCSecurityPrivate' is not supported by server.'

**Comment by romanett** [comment]
ua com interop was deprecated as of 11/2024
