### ISSUE TITLE
Need MAUI sample application.

### ISSUE THREAD

**Issue by EvilEyeTK** [OPCFoundation/UA-.NETStandard-Samples#616]
### Type of issue

- [ ] Bug
- [x] Enhancement
- [ ] Compliance
- [ ] Question
- [X] Help wanted

### Current Behavior
Microsoft ended support for all Xamarin, on May 1, 2024.
### Expected Behavior
We need sample application using MAUI, the successor to Xamarin.

**Comment by mregen** [comment]
Hi @EvilEyeTK and community, we need a volunteer to update the Xamarin sample for MAUI!

**Comment by romanett** [comment]
xamarin was deprecated as of 11/2024
