### ISSUE TITLE
UA Com Server Wrapper Subscription Failure after 10K Nodes

### ISSUE THREAD

**Issue by rootfixxxer** [OPCFoundation/UA-.NETStandard-Samples#634]
### Type of issue

- [X] Bug
- [ ] Enhancement
- [ ] Compliance
- [ ] Question
- [ ] Help wanted

### Current Behavior

For example using UA Expert, when creating a new subscription with more than 10k of items, some of the tags start to fail saying that the StatusCode is Bad.

### Expected Behavior

All the tags/items should be Good no matter the number.

### Steps To Reproduce

1. Configure the XML to use the DA Server with the tags/items
2. Run the Com Server Wrapper
3. Connect with UA Expert or other tool
4. Create a new subscription and add a couple of tags/items
5. Keep adding tags/items
6. At some point (around 10k but not always), we start to see Bad tags for working ones
7. If we delete some of the tags/items and decrease the total amount in the same subscription, we can see that everything returns to the normal with Good tags

**NOTE**: This happens globally, what do I mean by this, if we have two or more subscriptions, I can get BAD  tags when the total amount of tags/items in all of the subscriptions are higher than the 10k, I can get BAD tags in one of the subscription that has for instance 1k. 

### Environment

```markdown
- OS: Windows 11
- Environment: n/a
- Runtime: .NET4.8
- Nuget Version: 1.5.374.78
- Component: ???
- Server: UA Com Server
- Client: UA Expert
```

**Comment by romanett** [comment]
ua com interop was deprecated as of 11/2024
