### ISSUE TITLE
UA Quickstart Application.sln: read and write node value from Server side.

### ISSUE THREAD

**Issue by meihkkkkkkk** [OPCFoundation/UA-.NETStandard-Samples#64]
**Hi, I'm working with an old version of project downloaded from this github, which still have "UA Quickstart Application.sln".

Here's what I understand:  

- When I run a Server from this solution, for example, the UserAuthenticaion Server, the Program.cs will call the ServerForm from "opc ua server controls". Then I have to modify the ServerForm to add a function of reading and writing node value from my OPC UA Server (I have done with Client, but I'm trying to add this to the Server).

- In ServerForm code, I try to do this:
```       TimestampsToReturn axxxx = new TimestampsToReturn();
         ReadValueIdCollection list = new ReadValueIdCollection();
         DataValueCollection result = new DataValueCollection();
         DiagnosticInfoCollection diag = null;
         ReadValueId _value = new ReadValueId();
         _value.NodeId = new NodeId("ns=2;s=abc2");
          list.Add(_value);
          m_server.Read(null, 1000, axxxx, list, out result, out diag);
          label9.Text = result[0].Value.ToString
```
(`m_server` is defined as Opc.Ua.Server.StandardServer in the original code)
But when I run this code, I think the `m_server.Read()` causes error "BadRequestHeaderInvalid" with this line inside UserAuthenticationServer.cs:
![image](https://user-images.githubusercontent.com/59635254/90335209-64422d80-dffd-11ea-959e-180c47de2fe2.png)
It's the same when I trying to write node value.

Can you give me some solution about this? Thank you**

**Comment by mregen** [comment]
Hi @meihkkkkkkk , there is now a sample to access a service directly in the https://github.com/OPCFoundation/UA-.NETStandard/tree/master/Tests/Opc.Ua.Server.Tests project.
