### ISSUE TITLE
Why Are Samples Provided With Windows GUIs?

### ISSUE THREAD

**Issue by 7enderhead** [OPCFoundation/UA-.NETStandard-Samples#649]
### Type of issue

- [ ] Bug
- [ ] Enhancement
- [ ] Compliance
- [ ] Question
- [ ] Help wanted

### Current Behavior

You need a Windows version of .NET to make the samples work.

### Expected Behavior

I want the samples to work on any .NET platform. They can be command line based. I cannot change my OS just to take a look at the samples, of which the important part is hidden in some GUI-heavy program.

### Environment

```markdown
- OS: any other than Windows
```

**Comment by romanett** [comment]
@7enderhead for this usecase we have the Reference Client & Server in the Main repository
