### ISSUE TITLE
upgrade samples to Netcore 3.1

### ISSUE THREAD

**Issue by eoursel** [OPCFoundation/UA-.NETStandard-Samples#65]
Hi @mregen 

Any reason for not upgrading the NetCoreSampleServer and NetCoreSampleClient to Netcore 3.1 (still 2.1) which is LTS at Microsoft? 

Regards

**Comment by mregen** [comment]
yes indeed, netcore 3.1 and 2.1 have LTS, it could be upgraded. Just this repo is now community maintained so looking for volunteers...:-)

**Comment by mregen** [comment]
done
