### ISSUE TITLE
Alarms & Conditions example cannot retrieve the ConditionId event field on Siemens PLC

### ISSUE THREAD

**Issue by htbmw** [OPCFoundation/UA-.NETStandard-Samples#650]
### Type of issue

- [X] Bug
- [ ] Enhancement
- [ ] Compliance
- [ ] Question
- [ ] Help wanted

### Current Behavior

Using the Alarms & Conditions example under the Workshop folder, it was discovered that the ConditionId event field is always null when running it against a real Siemens PLC.

When running it against the reference server (virtual opcua server) it works, so it is not 100% sure where the fault is:
Is it on the reference server, or is it in the Siemens PLC firmware?

This is the line that is problematic:

https://github.com/OPCFoundation/UA-.NETStandard-Samples/blob/7708a11ebef8934a4c0d6baacb803eb6593d3d3c/Workshop/AlarmCondition/Client/FilterDefinition.cs#L128

![image](https://github.com/user-attachments/assets/7658fd9d-1473-4943-8c8b-7f25d735aab5)

When I change it to 

`operand.TypeDefinitionId = ObjectTypeIds.ConditionType,`

then it works on both the Siemens PLC and reference opcua server.

### Expected Behavior

Not 100% where the error is, therefor not sure if BaseEventType in the example should still work and Siemens should fix the FW, or if the example is wrong and should be using ConditionType?

Since it makes sense that a ConditionId should be defined on the ConditionType, I am leaning towards the error being in the example and the reference server.
If the correct way to select the ConditionId is by specifying the ConditionType, then the reference server should not create a false positive by returning a ConditionId when using the incorrectly specified BaseEventType.

### Environment

```markdown
- OS:
- Environment:
- Runtime:
- Nuget Version:
- Component:
- Server:
- Client:
```

**Comment by Archie-Miller** [comment]
I can confirm that the Reference Server does return a ConditionId, whether the BaseEventType or the ConditionType is requested as the type definition.

I can also confirm that typically when requesting a ConditionId, the type definition is usually ConditionType.  This is true of the Foundation Compliance Test Tool, and separate server.

However the spec is not entirely clear on whether this case should be restricted.  Considering that the select field is specifically for a nodeId, it could certainly be possible that a client could want a nodeId for a specific event that does not fall under the category of Alarms/Acknowledgeable events.

It would be good to get a clarification from the author of Part Nine.

**Comment by htbmw** [comment]
@Archie-Miller Thanks for the reply and the PR, appreciate that!
It gives more reassurance that the use of the ConditionType is correct and not some sort of a hack. ;-)
